### ISSUE TITLE
Is there a plan to publish to npm?

### ISSUE THREAD

**Issue by daGaiGuanYu** [arianrhodsandlot/retroarch-emscripten-build#1]
If we can install these files, then we could make an web app which could run without internet access (LAN access).  
In some areas, cdn is not that fast like other places.

**Comment by arianrhodsandlot** [comment]
There is no such plan, since these files are too large to install (over 500MB), and they cannot be "imported" to run by another script directly like an ordinary npm package.

If speed is your concern, I would recommend you to:
1. Download the archive from [buildbot.libretro.com](https://buildbot.libretro.com/stable/1.16.0/emscripten/) or from this repository. In fact, they are exactly the same.
2. Pick the cores you need, copy them to your codebase manually or host them somewhere else. You might not need all cores, so the overall size can be acceptable.

If you think npm is more suitable for you, feel free to publish one of your own. Again, the files in this repo are just a copy from [buildbot.libretro.com](https://buildbot.libretro.com/stable/1.16.0/emscripten/) without any change.

**Comment by daGaiGuanYu** [comment]
Thank you!
